package:
    name: gdsfactory
    version: "2.1.3"

source:
    path: ..

build:
    number: 0
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv

requirements:
    host:
        - pip
    build:
        - python>=3.6
        - click
        - gitpython
        - gdspy
        - omegaconf
        - jsondiff
        - klayout
        - numpy
        - pandas
        - phidl
        - picwriter
        - pyqtree
        - qrcode
        - rectpack
        - scipy
        - shapely
        - networkx
        - matplotlib
        - pytest

    run:
        - python>=3.6
        - numpy
        - scipy
        - opencv

test:
    imports:
        - gdsfactory

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python libraries to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joaquin
